### ISSUE TITLE
QC beamb misalignment exaggerate echoes

### ISSUE THREAD

**Issue by andershenja** [baltrad/beamb#1]
The quality control se.smhi.detector.beamblockage appears to exaggerate echoes in sectors of heavy blockage.
Possible causes may be that the topographical model is misaligned with respect to actual detectability and too high tolerance before sector is considered completely blocked.
Two images attached to illustrate exaggerated echoes. The imagery are focused on two affected radars in Norway: Røst and Hasvik
![balder-tst_blockage_20170123_0900z](https://user-images.githubusercontent.com/32340067/133738157-ed8d1f3a-a055-4fbc-81c7-b3e6a09c03c7.jpg)
![balder-tst_blockage_20170120_0500z](https://user-images.githubusercontent.com/32340067/133738163-cb7c407f-aa28-466d-ace3-50ed3cf76572.jpg)

**Comment by guntherhaase** [comment]
The same applies to Swiss data. It would be beneficial to configure each radar individually, i.e. setting the limit of the Gaussian approximation of the main lobe (--beamwidth=BEAMWIDTH) and the threshold for correcting beam blockage individually per radar (--restore=RESTORE), similar to https://github.com/baltrad/bropo/blob/master/config/ropo_options.xml. Hence, it would be possible to consider different DEM resolutions.

**Comment by andershenja** [comment]
Defined by #11, added in beamb-build-79.
