### ISSUE TITLE
bin/beamb defaults should be defined by pybeamb/beamb_defines.py

### ISSUE THREAD

**Issue by dljo** [baltrad/beamb#8]
Defaults in bin/beamb, e.g. https://github.com/baltrad/beamb/blob/master/bin/beamb#L86 should be the same as defined in pybeamb/beamb_defines.py. Currently, they are hardcoded so have equal values. 

Proposed solution: Import pybeamb/beamb_defines.py in bin/beamb

**Comment by andershenja** [comment]
Added in beamb-build-82
